class Saham {
  int? tickerId; // This can be null until it's generated by SQLite
  String ticker;
  int open;
  int high;
  int last;
  double change;

  Saham({
    this.tickerId, // Nullable
    required this.ticker,
    required this.open,
    required this.high,
    required this.last,
    required this.change,
  });

  // Convert Saham object into a Map for SQLite
  Map<String, dynamic> toMap() {
    return {
      'tickerId': tickerId, // If null, SQLite will generate it
      'ticker': ticker,
      'open': open,
      'high': high,
      'last': last,
      'change': change,
    };
  }

  // Convert Map from SQLite to Saham object
  factory Saham.fromMap(Map<String, dynamic> map) {
    return Saham(
      tickerId: map['tickerId'], // Nullable
      ticker: map['ticker'],
      open: map['open'],
      high: map['high'],
      last: map['last'],
      change: map['change'],
    );
  }
}
